name: Build and push image
description: "Build image"
inputs:
  context:
    description: 'context path'
    required: false
    default: "."
  dockerfile:
    description: 'Dockerfile path'
    required: false
    default: "Dockerfile"
  tag:
    description: 'Image tag'
    required: true
  target:
    description: 'Build target'
    required: false
  app_version:
    description: 'App version'
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup docker context for buildx
      id: buildx-context
      shell: sh
      run: |
        if ! docker context ls | grep builders; then
          docker context create builders
        fi
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        endpoint: builders
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ inputs.tag }}
        target: ${{ inputs.target }}
        pull: true
        build-args: |
          BUILD_MODE=development
          APP_VERSION=${{ inputs.app_version }}
          IMAGE_SOURCE=${{ github.server_url }}/${{ github.repository }}
