extends: default

ignore: |
  /bin/
  /public/
  /var/
  /vendor/

rules:
  document-start: disable
  line-length: disable
  braces: { min-spaces-inside: 1, max-spaces-inside: 1, min-spaces-inside-empty: 0, max-spaces-inside-empty: 0 }
  empty-lines: { max: 1 }
  indentation:
    spaces: 2
    indent-sequences: true
  comments:
    require-starting-space: false
    min-spaces-from-content: 1
  comments-indentation: disable
