doctrine:
  dbal:
    url: '%env(resolve:DB_DSN)%'
    options: # options could be overridden by the DSN
      # https://php.net/manual/en/pdo.constants.php#pdo.constants.attr-timeout
      2: 2
    # IMPORTANT: You MUST configure your server version,
    # either here or in the DB_DSN env var (see .env file)
    # server_version: '13'

when@prod:
  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'
