name: 'Composer auth.json'
description: 'Create an auth.json file with a github auth activated'
inputs:
  github_token:
    description: 'GITHUB_TOKEN to use'
    required: true
  php_packages_user:
    description: 'Username for private packages repository'
    required: true
  php_packages_password:
    description: 'Password for private packages repository'
    required: true

runs:
  using: "composite"
  steps:
    - run: >
        echo "{\"github-oauth\": {\"github.com\": \"${{ inputs.github_token}}\"}, \"http-basic\":{\"php-packages.shippeo.cloud\":{\"username\": \"${{ inputs.php_packages_user}}\", \"password\": \"${{ inputs.php_packages_password}}\"}}}" > srv/app/auth.json
      shell: sh
